#!/bin/bash
#
# Small setup script that enables the
# user to pull scripts as shell functions in their
# shell session.
set -e

SHELLFUNCS_REPO_PATH=$PWD
SCRIPTS_PATH="$SHELLFUNCS_REPO_PATH/scripts"
BASHRC_PATH=$HOME/.bashrc
{
    echo "SHELLFUNCS_REPO_PATH=$SHELLFUNCS_REPO_PATH"
    echo "SCRIPTS_PATH=$SCRIPTS_PATH"
    echo ""
    cat _setup
} >> "$BASHRC_PATH"
