#!/bin/bash
#
# These are common tests for all the 
# shellfunc test scripts.

shellfunc_loaded () {
	# is the shellfunc loaded into the shell session?
	if [ -z "$DEBUG" ]; then
		type "$PROGRAM_NAME" > /dev/null 2>&1
	else
		type "$PROGRAM_NAME" 
	fi
	EXIT_STATUS="$?"
	assertEquals "$PROGRAM_NAME is not in current shell session" 0 "$EXIT_STATUS"
	
	# NOTE: return 0 is needed at the moment because otherwise one failure is counted twice
	# TODO(conner@conneracrosby.tech): monitor this issue to see if this gets fixed in future releases
	# https://github.com/kward/shunit2/pull/140
	return 0
}

shellfunc_noninteractive_exec () {
	# shellcheck disable=2086
	# NOTE2: We want word splitting for $ARGS, otherwise all args are a string!
	set -- "$PROGRAM_NAME" $ARGS
	if [ -z "$DEBUG" ]; then
		"$@" > /dev/null 2>&1
	else
		"$@"
	fi
	EXIT_STATUS="$?"
	# unsets program with args set above 
	set --
	assertEquals "$PROGRAM_NAME returned a non-zero status code" 0 "$EXIT_STATUS"
	return 0
}

shellfunc_interactive_exec () {
	# shellcheck disable=2086
	# NOTE2: We want word splitting for $ARGS, otherwise all args are a string!
	set -- "$PROGRAM_NAME" $ARGS
	if [ -z "$DEBUG" ]; then
		echo "$STDIN_TO_PROGRAM" | "$@" > /dev/null 2>&1
	else
		echo "$STDIN_TO_PROGRAM" | "$@"
	fi
	EXIT_STATUS="$?"
	# unsets program with args set above 
	set --
	assertEquals "$PROGRAM_NAME returned a non-zero status code" 0 "$EXIT_STATUS"
	return 0
}
