#!/bin/bash
#
# shellcheck disable=1090

#######################################
# Usage string for the program.
# Globals:
#   PROGRAM_NAME
# Outputs:
#   - usage heredoc string to stdout
# Returns:
#   0 - cat success
#   1 - cat error
#######################################
usage() {
	cat << _EOF_
Usage: $PROGRAM_NAME [-d] [-h] [-t TEST_PROGRAM]

This script handles the running of tests for the project.

Options:
	-d	allows tests to display all output (debug)
	-h	display usage str and exit
	-t	specify a single test program/script to run

_EOF_
	return
}

#######################################
# Used to run tests. Allows in defined 
# cases to rerun program(s), only if 
# re-running requires subtle changes.
# Globals:
#   SUDOER_PASSWORD
#   SKIPPING_TEST_MESSAGE
#   SHELLFUNCS_TEST_SCRIPTS_ENV_PATH
#	REQUIRES_SUDOER_PASSWORD
#	TRYING_TEST_AGAIN_MESSAGE
# Arguments:
#   $1: program/script name
#   $2: previous status code of the program/script ($1)
# Outputs:
#   - Success/error messages to stdout
# Returns:
#   0 - general success
#   1 - general error
#	REQUIRES_SUDOER_PASSWORD
#######################################d
run_test_program() {
	FILENAME="$1"
	PREVIOUS_STATUS_CODE="$2"

	# there shouldn't be a default case (like '*)'), as PREVIOUS_STATUS_CODE
	# should either be empty or contain some positive int
	# NOTE: this is just to try and rerun scripts if the change is subtle
	case "$PREVIOUS_STATUS_CODE" in
	"$REQUIRES_SUDOER_PASSWORD")		if [ -z "$SUDOER_PASSWORD" ]; then echo "${FILENAME}: SUDOER_PASSWORD not set! $SKIPPING_TEST_MESSAGE"; return 1; fi
										echo "$SUDOER_PASSWORD" | sudo --validate --stdin; 
										;;
	"")									;;
	esac

	"${PWD}/$FILENAME"; EXIT_STATUS="$?"
	
	if [ "$EXIT_STATUS" = "$PREVIOUS_STATUS_CODE" ]; then
		echo "${PROGRAM_NAME}: tried to re-run script in a known way, but got same error"
		echo "${PROGRAM_NAME}: either issue not fixed or shellfunc actually returned such status code?"
		return $EXIT_STATUS
	fi

	case "$EXIT_STATUS" in
	"$REQUIRES_SUDOER_PASSWORD")		echo "${FILENAME}: $TRYING_TEST_AGAIN_MESSAGE"
										run_test_program "$FILENAME" "$REQUIRES_SUDOER_PASSWORD"
										;;
	*)									return $EXIT_STATUS
										;;
	esac
}

#######################################
# Not a function at the moment, but can be considered
# the main of the program.
#######################################
# NOTES: set -e might not be needed as the driver probably
# should be ok with reporting non-zero status codes of each test ran.
# loads test env needed to run tests
. "$SHELLFUNCS_TEST_SCRIPTS_ENV_PATH"

# NOTE: opt is unset incase it has been defined previously;
# getops will place the next option (e.g. o, t) into name;
unset opt
while getopts "dht:" opt; do
	case "$opt" in
	"d")	export DEBUG="true"
			;;
	"h")	usage
			exit 0
			;;
	"t")    TEST_PROGRAMS=$OPTARG
			;;
	":")    echo "${PROGRAM_NAME}: an argument is required for -- $OPTARG"
			exit 1
			;;
    *)		# NOTE: using the program with no arguments will cause '?'
			# to be inserted into $opt. However, I've found getopts seems to
			# handle unknown options (at least those not found in the opt str).
			# 'shellcheck' seems to say otherwise, and that a default case is needed.
			usage
			exit 1
			;;
    esac
done

# for now the default will be to run all test programs
# NOTE: globbing pattern should be generalized with exceptions
# being handled in the below case statement
if [ -z "$TEST_PROGRAMS" ]; then
	TEST_PROGRAMS="*"
fi

for f in $TEST_PROGRAMS
do
    case "$f" in
		"$(basename "$SHELLFUNCS_TEST_SCRIPTS_ENV_PATH")")		;;
		"$(basename "$0")")										;;
		"common_tests")											;;
		"shunit2")												;;
		*)														echo "${f}: running test(s)"
																run_test_program "$f"
																;;
	esac
done

exit 0
