#!/bin/bash
#
# shellcheck disable=1091,2005,1090,2086

. "$SHELLFUNCS_TEST_SCRIPTS_ENV_PATH"

# check to see if a password be required to run sudo
if [ "$(sudo --non-interactive true 2>&1)" != "" ]; then
    echo "${PROGRAM_NAME}: must have sudoer password to run script!"
    exit $REQUIRES_SUDOER_PASSWORD
fi

suite () {
	# suite_addTest has to be used, else shunit2 will not
	# execute any other shell functions in the env (this applies to common_tests)
	suite_addTest shellfunc_loaded
	# NOTE: smtp client allows a user to edit the dotfile 
	# through an editor of choice, for now I will just skip this.
	export ARGS="-a n"
	suite_addTest shellfunc_interactive_exec
}

# NOTE: . does not check PWD for script by default
. "./common_tests"

# load shUnit2 (https://github.com/kward/shunit2.git)
. "./shunit2"
