#!/bin/bash
#
# shellcheck disable=1091,2005

oneTimeSetUp () {
	. "./.env"
	SHELLFUNC_NAME="$(echo "$(basename "$0")" | grep --only-matching --perl-regexp "(?<=.{${#TESTFILE_PREFIX}})(.+)")"
}

suite () {
	# suite_addTest has to be used, else shunit2 will not
	# execute any other shell functions in the env (this applies to common_tests)
	suite_addTest testshellfunc_loaded
	suite_addTest testshellfunc_exec
}

# NOTE: . does not check PWD for script by default
. "./common_tests"

# load shUnit2.
. "./shunit2"

