#!/bin/bash
#
# shellcheck disable=1091,2005

. "./.env"

GLOBBING_PATTERN='/dev/vmnet*'

set -- "$GLOBBING_PATTERN"
if [ "$1" = "$GLOBBING_PATTERN" ]; then
	echo "${PROGRAM_NAME}: vmnet devices do not exist. $SKIPPING_TEST_MESSAGE"
	exit 0
fi

suite () {
	# suite_addTest has to be used, else shunit2 will not
	# execute any other shell functions in the env (this applies to common_tests)
	suite_addTest testshellfunc_loaded
	suite_addTest testshellfunc_exec
}

# NOTE: . does not check PWD for script by default
. "./common_tests"

# load shUnit2.
. "./shunit2"

