#!/bin/bash
#
#

#######################################
# Used to run the bootinfoscript utility
# Outputs:
#   Hard disk information in relation to bootloaders
#######################################
bootinfoscript () {
    cd "$(dirname "$(which bootinfoscript)")";
    sudo ./bootinfoscript --stdout; 
    cd - > /dev/null;
    return
}
