#!/bin/bash
#
# Part of 'shellfuncs' git repo

#######################################
# A 'less' wrapper but for shullfuncs 
# scripts. Perhaps in the future, arguments past 1
# could be passed in as additional options to less (e.g. --foo, -b).
# Globals:
#   SCRIPTS_PATH
# Arguments:
#   $1: the shellfuncs script name to pass as 
#       an argument to less
# Returns:
#   0 - general success
#   1 - general error
#######################################
shellfuncs_less () {
    # shellcheck disable=SC1091
    less "${SCRIPTS_PATH}/${1}" || return 1
    return 0
}

#######################################
# Bash tab completion for shellfuncs_less,
# displays all scripts in SCRIPTS_PATH.
# Globals:
#   SCRIPTS_PATH
# Outputs:
#   shellfunc scripts that can be viewed
# Returns:
#   0 - general success
#   1 - general error
#######################################
_shellfuncs_less_completion () {
    complete -W "$(ls "${SCRIPTS_PATH}")" shellfuncs_less || return 1
    return 0
}

_shellfuncs_less_completion
