#!/bin/bash
#
# Part of 'shellfuncs' git repo

#######################################
# Installation prompt for other scripts. The purpose
# of running any of these scripted software installs
# would be to setup software in a preferred way on 
# a new machine. A new machine is defined as a recently
# installed distro with very few 'things' installed.
# Things in this case could be numerous in type such as
# public/private keys, packages, etc.
# Globals:
#   OTHER_SCRIPTS_PATH
# Outputs:
#   - Success/error messages to stdout
#######################################
shellfuncs_new_devmachine_setup (){
    cat << _EOF_

Scripted software installs:

1. IDE/Editor
2. Hypervisor
3. SMTP Client
0. Quit (default)

_EOF_
    # TODO are all of these flags needed for read?
    read -r -e -p "Enter selection to run [0-3]: " SELECTION_REPLY
    case "$SELECTION_REPLY" in
    1)  # shellcheck disable=SC1090
        source "${OTHER_SCRIPTS_PATH}/shellfuncs_setup_editor"
        shellfuncs_setup_editor
        return
        ;;
    2)  # shellcheck disable=SC1090
        source "${OTHER_SCRIPTS_PATH}/shellfuncs_setup_hypervisor"
        shellfuncs_setup_hypervisor
        return
        ;;
    3)  # shellcheck disable=SC1090
        source "${OTHER_SCRIPTS_PATH}/shellfuncs_setup_smtp_client"
        shellfuncs_setup_smtp_client
        return
        ;;
    *)  echo "exited"
        return 0
        ;;

    esac
}
