#!/bin/bash
#
# Part of 'shellfuncs' git repo

#######################################
# Displays codium extensions that have an
# updated version through Visual Studio Code's
# Marketplace. Marketplace link below:
# https://marketplace.visualstudio.com/vscode
#
# Outputs:
#   Extension name with the newer/local version number,
#   it is assumed the marketplace version will never
#   be older than what is locally installed.
#######################################
shellfuncs_show_codium_exts_updates () {
    for extension in $(codium --list-extensions --show-versions); do
        # codium returns an extension as extension@local_version (e.g. gerane.Theme-Boron@0.0.7)
        IFS='@' read -r extension_name local_version <<< "$extension"
        marketplace_version="$(wget -qO - https://marketplace.visualstudio.com/items?itemName="$extension_name" | grep -ohE "\"VersionValue\":\"[0-9\.]+\"" | grep -oh "[0-9].*[0-9]")"
        if [[ -n "$marketplace_version" ]]; then
            # assuming extension version on marketpkace is ALWAYS newer
            if [[ "$marketplace_version" != "$local_version" ]]; then
                echo "$extension_name can be upgraded to version: $marketplace_version, installed: $local_version"
            fi
        fi
    done
    return
}
