#!/bin/bash
#
# Part of 'shellfuncs' git repo

#######################################
# A 'less' wrapper but for shullfuncs 
# scripts.
# Globals:
#   SHELLFUNCS_SCRIPTS_PATH
# Arguments:
#   $1: the shellfuncs script name to pass as 
#       an argument to less
#   $n: any options you would usually pass to less
# Returns:
#   0 - general success
#   1 - general error
#######################################
shellfuncs_less () {
    # shellcheck disable=SC1091
    OPTIONS=
    while [ $((${#}-1)) != 0 ]; do
        OPTIONS="${OPTIONS} ${1}"
        shift
    done
    FILENAME_PATH="${SHELLFUNCS_SCRIPTS_PATH}/${1}"
    # shellcheck disable=2086
    # NOTE: We want word splitting for $OPTIONS, otherwise all args are one string!
    set -- "$(which less)" $OPTIONS "$FILENAME_PATH"
    # last positional argument should be filename
    "$@" || return 1
    return 0
}

#######################################
# Bash tab completion for shellfuncs_less,
# displays all scripts in SHELLFUNCS_SCRIPTS_PATH.
# Globals:
#   SHELLFUNCS_SCRIPTS_PATH
# Outputs:
#   shellfunc scripts that can be viewed
# Returns:
#   0 - general success
#   1 - general error
#######################################
_shellfuncs_less_completion () {
    complete -W "$(ls "${SHELLFUNCS_SCRIPTS_PATH}")" shellfuncs_less || return 1
    return 0
}

_shellfuncs_less_completion
