#!/bin/bash
#
# Part of 'shellfuncs' git repo
# Inspired by: https://stackoverflow.com/questions/344317/where-does-gcc-look-for-c-and-c-header-files

#######################################
# Prints where the c++ preprocessor looks for 
# includes.
# Outputs:
#   Directories where preprocessor looks for 
#   includes
# Returns:
#   0 - general success
#   1 - general error
#######################################
shellfuncs_gpp_includes() {
    "$(gcc -print-prog-name=cc1plus)" -v -E - < /dev/null || return 1
    return 0
}
