#!/bin/bash
#
# Part of 'shellfuncs' git repo

#######################################
# Used to show basic options for gnu c++ compiler.
# Outputs:
#   Basic compilation options 
#######################################
shellfuncs_g++_basic_options () {
    g++ --help | grep -e "-o\s\|-[c]\s\|-[S]\|-[E]"
    return
}
