#!/bin/bash
#
# Part of 'shellfuncs' git repo

#######################################
# Installation prompt for other scripts. The purpose
# of running any of these scripted software installs
# would be to setup software in a preferred way on 
# a new machine. A new machine is defined as a recently
# installed distro with very few 'things' installed.
# Things in this case could be numerous things such as
# public/private keys, packages, etc.
# Outputs:
#   - Success/error messages to stdout
#######################################
shellfuncs_new_devmachine_setup (){
    cat << _EOF_

Scripted software installs:

1. IDE/Editor
0. Quit (default)

_EOF_
    read -r -e -p "Enter selection to run [0-1]: " SELECTION_REPLY
    case "$SELECTION_REPLY" in
    1)  # shellcheck disable=SC1090
        source "${OTHER_SCRIPTS_PATH}/shellfuncs_setup_editor"
        setup_editor
        ;;
    *)  echo "exited"
        return
        ;;

    esac
}
