#!/bin/bash
#
# Part of 'shellfuncs' git repo

#######################################
# Used to upgrade all deb packages except those
# pertaining to grub.
# Outputs:
#   Normal apt-get installation output
# Returns:
#   0 - general success
#   1 - general error
#######################################
shellfuncs_upgrade_all_without_grub () {
    sudo apt-get list --upgradable \
    | grep --invert-match grub \
    | cut --fields=1 --delimiter="/" \
    | tail --lines=+2 \
    | xargs --delimiter='\n' -- sudo apt-get install --assume-yes
    return
}
