#!/bin/bash
#
# Part of 'bashutils' git repo

#######################################
# Used to upgrade all deb packages except those
# pertaining to grub.
# Outputs:
#   Normal apt installation output
#######################################
upgrade_all_without_grub () {
    sudo apt list --upgradable \
    | grep -v grub \
    | cut -f1 -d"/" \
    | tail -n +2 \
    | xargs -d '\n' -- sudo apt install -y 
    return
}
