#!/bin/bash
#
# Part of 'shellfuncs' git repo

#######################################
# Used to run the bootinfoscript utility
# Outputs:
#   Hard disk information in relation to bootloaders
#######################################
bootinfoscript () {
    cd "$(dirname "$(which bootinfoscript)")" || exit;
    sudo ./bootinfoscript --stdout; 
    cd - > /dev/null || exit;
    return
}
