#!/bin/bash
#
# Part of 'shellfuncs' git repo
# Executable can be found here: https://sourceforge.net/projects/bootinfoscript/

#######################################
# Used to run the bootinfoscript utility,
# assumes 'bootinfoscript' can be found through PATH.
# Outputs:
#   Hard disk information in relation to bootloaders
# Returns:
#   0 - general success
#   1 - general error
#######################################
shellfuncs_bootinfoscript() {
    cd "$(dirname "$(which bootinfoscript)")" || return 1
    sudo ./bootinfoscript --stdout || return 1
    cd - > /dev/null || return 1
    return 0
}
